// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-57nJrLaqGiG11158PWydy0NZo4esf3o',
    appId: '1:68852307398:web:43c4834009c1e3ea840ec7',
    messagingSenderId: '68852307398',
    projectId: 'coachlife-1bf59',
    authDomain: 'coachlife-1bf59.firebaseapp.com',
    storageBucket: 'coachlife-1bf59.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpUvrgOLXPP4a3e3stTYN1lJ0aFo9JciQ',
    appId: '1:68852307398:android:bac2567d50b057b7840ec7',
    messagingSenderId: '68852307398',
    projectId: 'coachlife-1bf59',
    storageBucket: 'coachlife-1bf59.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3Q1jRH84gRkY-OUmV5U1ndU7I2Lk6Arg',
    appId: '1:68852307398:ios:62b3cf7788d191c7840ec7',
    messagingSenderId: '68852307398',
    projectId: 'coachlife-1bf59',
    storageBucket: 'coachlife-1bf59.appspot.com',
    iosBundleId: 'com.social.coachLife',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3Q1jRH84gRkY-OUmV5U1ndU7I2Lk6Arg',
    appId: '1:68852307398:ios:e5fe7574830aa986840ec7',
    messagingSenderId: '68852307398',
    projectId: 'coachlife-1bf59',
    storageBucket: 'coachlife-1bf59.appspot.com',
    iosBundleId: 'com.example.coachLife',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-57nJrLaqGiG11158PWydy0NZo4esf3o',
    appId: '1:68852307398:web:804788fdad8758bc840ec7',
    messagingSenderId: '68852307398',
    projectId: 'coachlife-1bf59',
    authDomain: 'coachlife-1bf59.firebaseapp.com',
    storageBucket: 'coachlife-1bf59.appspot.com',
  );

}